README.md
so we have a common point of reference
=> added original game to README

.github/workflows/test.yml, README.md
Jeg lavede ændringer i, hvordan afspilleren svæver gennem rummet, med at glide og gå i den retning, den vendte mod, jeg lavede nogle funktioner med at ændre retningen, men jeg gjorde ikke meget, _fordi det ikke var min opgave._ Jeg fik info fra her: [https://api.arcade.academy/en/latest/examples/sprite_move_angle.html#sprite-move-angle](url)
=> Player floats through space!

my_game.py
=> The player has lives

my_game.py
very small error fixed - a simple re-formulation.
=> fixed bug with ufos not dying when out of bounds

my_game.py
The asteroids now start in the middle.
=> The astroid now starts in the middle.

my_game.py
5 asteroids now start at a random location
=> Made 5 astroids spawn at a random location.

my_game.py
The Asteroids now move in a random direction, there is no wrapping.
=> The astroids now move in different directions

my_game.py
added the wrapping mechanic. There are multible ways to make the feature work - this one seemed like the best but see for youself as well.
=> added wrapping to the player object

my_game.py
#43 and #33
created a function to let any sprite wrap.
Added it in .update for; Asteroid, PlayerShot and Player.
Can be considered to be added to UFOShot.
=> Universal wrap function

my_game.py
The UFO has a different random scale now!
=> The ufo has a different size

my_game.py
Player cannot go faster than max speed
=> Player has max speed

my_game.py
=> Change the background color

my_game.py
fixed the bug. It was relatively simple and straightforward. Hope to merge it as quickly as possible.
=> BUG_FIXED: made UFOShot disappear when hitting the player.

my_game.py
tried to restore the file to the correct version, with all features intact. The program is running fine now.
=> Cleanup from view conversion

my_game.py
=> Asteroids now rotate

my_game.py
You cannot now shoot when you're respawning.
You can see when you're respawning and not dead
=> Respawning shoot glitch + respawning effect

my_game.py, my_game.toml
#81
fairly simple and small fix here. only a few lines of code nescessary.
=> added wrapping and range to the ufo shot

my_game.py
Level increments when all Asteroids have been shot. We need to:
- Make the game harder on level increase
- Make the player realize that the level was cleared (maybe a message)
=> Add level feature

my_game.py
I changed the scaling system for the asteroids to this:
They no longer use four different files for their sizes. - They use one file and their size then determines the scaling of that file. (multiplied with SPRITE_SCALING of course)
And i increased their scale.
They now always drop with 1x scaling at a time
=> scaled up the Asteroids and changed their scaling system.

my_game.py
forgot to change my variable name in game file last merge...
simple change - should make this one short lived
=> corrected variable names

my_game.py
fixed the bug. Super simple fix - just one line changed.
Added a comment to the loop, just for clarity.
=> fixed bug + added comment

my_game.py
fixed #104
Player now respawns when hit by ufo shot. Really simple one-line-fix.
Hope to merge it quickly
=> added reset function to ufo collision check.

my_game.py, my_game.toml
The exact same as PlayerShotFade 1
=> PlayerShotFade The Sequel.

my_game.py, my_game.toml
The ufo shot now fades and disappears
=> UfoShotFade

my_game.py
Created the universal shot class. The program works fine. The features were sort of intertwined so it was hard to split into fewer commits. But hopefully we can merge it without too much trouble.
=> Shot class

my_game.py, my_game.toml
Now you can restart in-game. This means that by pressing r you instantlty start a new game, with fresh lives and score.
This is an experimental feature and i would love to hear your opinions on wether it should be in the game.
=> added quick restart to the button R.

my_game.py, tools.py
Made the new (CLASS) in tools.py and added it onto the game, looks great. Could add some more, but I need to fix glitches first :)
=> Made thrust class.

game_sprites.py, my_game.py
You can now alter the time scale for each object, by changing their speed_scale.
=> Made all objects take the speed_scale modifier

game_sprites.py, my_game.py, tools.py
the speed scale feature needs to also affect:
* pitch of sounds created by their associated sprites
* fire rate and shot speed from the sprite
* paticle effects created by the sprite
* other things associated with the sprite
=> Expand time scale feature
